version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: config.settings.test
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
    DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    GOOGLE_API_KEY: changeme
    OPBEAT_ENABLED: False

phases:
  install:
    commands:
      - yum update -y
      - yum install -y maven curl wget
      - yum purge nodejs npm
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - yum install -y nodejs
      - node --version
  build:
    commands:
      - pip install -r requirements.txt
      - python manage.py
  post_build:
    commands:
      - echo Build completed on `date`
